@startjson
#highlight "**table**"
#highlight "supervisors"
#highlight "students"
#highlight "<color:green>report" / "**Entity**"
#highlight "<color:green>slides" / "**Entity**"
#highlight "<color:green>tasks" / "1"/ "**Entity**"
#highlight "<color:green>tasks" / "2" / "**Entity**"
#highlight "<color:green>tasks" / "3" / "**Entity**"
#highlight "**Entity**"
  {
    "**table**": "**projects**",
    "created_on": "(time object)",
    "deadline": "(time object)",
    "description": "Lorem ipsum...",
    "id": "(project ID)",
    "name": "(project name)",
    "<color:green>report": {
      "**Entity**": "**Artifact**",
      "comment": "",
      "grade": -1,
      "revisions": null
    },
    "<color:green>slides": {
      "**Entity**": "**Artifact**",
      "comment": "",
      "grade": -1,
      "revisions": null
    },
    "students": [
      "**array**",
      "opheliad",
      "jamesm",
      "arabellaf",
      "evelynd",
      "audreym"
    ],
    "supervisors": [
      "ronanf"
    ],
    "<color:green>tasks": [
      "**array**",
      { 
        "**Entity**": "**Task**",
        "assigned_to": "arabellaf",
        "created_on": "(time object)",
        "creator": "jamesm",
        "deadline": "(time object)",
        "discussion": "(discussion forest)",
        "name": "(task name)",
        "description": "Lorem ipsum...",
        "status": 0
      },
      {
        "**Entity**": "**Task**",
        "assigned_to": "opheliad",
        "created_on": "(time object)",
        "creator": "evelynd",
        "deadline": "(time object)",
        "discussion": "(discussion forest)",
        "description": "Lorem ipsum...",
        "name": "(task name)",
        "status": 2
      },
      {
        "**Entity**": "**Task**",
        "assigned_to": "arabellaf",
        "created_on": "(time object)",
        "creator": "jamesm",
        "deadline": "(time object)",
        "discussion": "(discussion forest)",
        "name": "(task name)",
        "description": "Lorem ipsum...",
        "status": 2
      }
    ]
  }
@endjson
