@startuml
hide footbox
autoactivate on
skinparam sequenceParticipant underline
actor ":User" as usr
control ":Project Controller" as ctl
entity ":Project" as db_prj
entity ":Project" as db_usr
entity ":quart_auth" as quart

usr -> ctl : // select info tab()
ctl -> quart : // check authentication()
ctl <-- quart : // authenticated
ctl -> db_prj : // check project id is in project database()
ctl <-- db_prj : // project id is in project database
ctl -> db_prj : // check current user is in project database()
ctl <-- db_prj : // current user is not a member of project
usr <-- ctl : // inform that current user is not a member of project
@enduml