image: debian/buster
arch: amd64
packages:
  - python3-pip
  - python3-venv
  - rethinkdb
  - wget
repositories:
  rethinkdb: https://download.rethinkdb.com/repository/debian-buster buster main 539A3A8C6692E6E3F69B3FE81D85E93F801BB43F
sources:
  - https://github.com/Huy-Ngo/acanban
tasks:
  - ipfs: |
      wget https://dist.ipfs.io/go-ipfs/v0.7.0/go-ipfs_v0.7.0_linux-amd64.tar.gz
      tar -xvzf go-ipfs_v0.7.0_linux-amd64.tar.gz
      sudo go-ipfs/install.sh
      rm -r go-ipfs*
      ipfs init
  - ci: |
      ipfs daemon &
      rethinkdb --no-http-admin &
      python3 -m pip install tox
      python3 -m tox -c acanban
  - cd: |
      if [[ $(git -C acanban tag --points-at HEAD) ]]
      then
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine
        python3 -m build --sdist --wheel acanban
        python3 -m twine upload acanban/dist/*
      fi
environment:
  PIP_PROGRESS_BAR: 'off'
secrets:
  - ee526a22-d848-4a9d-bb22-3b680b2bcc5a
