@startuml
hide footbox
autoactivate on
skinparam sequenceParticipant underline
actor ":User" as usr
control ":Project Controller" as ctl
entity ":quart_auth" as quart

usr -> ctl : // request creating project()
ctl -> quart : // check authentication()
ctl <-- quart : not authenticated 
usr <-- ctl : // user is not authenticated
@enduml