@startuml
hide footbox
autoactivate on
skinparam sequenceParticipant underline
actor ":User" as usr
control ":Project Controller" as ctl
entity ":quart_auth" as quart
entity ":User" as db_usr

usr -> ctl : // request creating project()
ctl -> quart : // check authentication()
ctl <-- quart : authenticated 
ctl -> db_usr : // check user's role()
ctl <-- db_usr : // new user is an assistant
usr <-- ctl : // inform that user is not allowed to create project
@enduml