@startuml
start
if (current user is not authenticated) then (yes)
  stop
endif
:extract project ID from request;
if (requested project does not exists) then (yes)
  stop
endif
if (current user is not member of project) then (yes)
  stop
endif
:retrieve project basic info from database;
:respond with rendered project info;
stop
@enduml
