@startuml
hide footbox
autoactivate on
actor ":Unauthorized User" as usr
boundary ":RegisterForm" as form
control ":RegisterController" as ctl
entity ":Account" as acc

usr -> form: // open registration page()
form -> form: // display form()
usr -> form: // submit form()
form -> ctl: // try adding user to database()
form <-- ctl !!: // raise value error()
deactivate form
deactivate form
@enduml
