@startjson
#highlight "**Entity**"
#highlight "discussion" / "0" / "**Entity**"
#highlight "discussion" / "1" / "**Entity**"
#highlight "discussion" / "0" / "comments" / "0" / "**Entity**"
#highlight "discussion" / "0" / "comments" / "1" / "**Entity**"
#highlight "discussion" / "0" / "comments" / "0" / "comments" / "0" / "**Entity**"
#highlight "discussion" / "0" / "comments" / "1" / "comments" / "0" / "**Entity**"
#highlight "discussion" / "1" / "comments" / "0" / "**Entity**"
#highlight "discussion" / "1" / "comments" / "1" / "**Entity**"
{
  "**Entity**": "**Task**",
  "assigned_to": "arabellaf",
  "discussion": [
    {
      "**Entity**": "**Comment**",
      "creator": "arabellaf",
      "content": "How to do this task?",
      "created_on": "(time object)",
      "comments": [
        {
          "**Entity**": "**Comment**",
          "creator": "jamesm",
          "content": "This may help:\\nhttps://example.org",
          "created_on": "(time object)",
          "comments": [
            {
              "**Entity**": "**Comment**",
              "creator": "arabellaf",
              "content": "Thanks but this\\nis irrelevant",
              "created_on": "(time object)",
              "comments": []
            }
          ]
        },
        {
          "**Entity**": "**Comment**",
          "creator": "evelynd",
          "content": "I found this link:\\nhttps://example.net",
          "created_on": "(time object)",
          "comments": [
            {
              "**Entity**": "**Comment**",
              "creator": "arabellaf",
              "content": "Wow this is really\\nhelpful, thanks.",
              "created_on": "(time object)",
              "comments": []
            }
          ]
        }
      ]
    },
    {
      "**Entity**": "**Comment**",
      "creator": "opheliad",
      "content": "Task #14 depends\\non this so can\\nyou resolve this\\nfaster? @arabellaf",
      "created_on": "(time object)",
      "comments": [
        {
          "**Entity**": "**Comment**",
          "creator": "evelynd",
          "content": "You can do #17\\nin the meantime",
          "created_on": "(time object)",
          "comments": []
        },
	{
          "**Entity**": "**Comment**",
	  "creator": "arabellaf",
	  "content": "Sure",
	  "created_on": "(time object)",
	  "comments": []
	}
      ]
    }
  ],
  "...": "..."
}
@endjson
