@startuml
node Client {
	node Browser
}

node Server {
	database "JSON-based\nDatabase" as db
	artifact "/etc/systemd/system/gpms.service" as systemd_conf
	component GPMS as gpms
	component hypercorn
	node systemd <<daemon>>
}

Browser --- hypercorn: HTTPS
hypercorn - systemd: run instance
systemd <- systemd_conf: configure
hypercorn -- gpms
gpms - db
@enduml
