@startuml
node Client {
	node Browser <<device>>
}
node Server {
	node NGINX as nginx <<load balancer>>
	database "JSON-based\nDatabase" as db
	file "/etc/systemd/system/gpms.service" as systemd_conf
	file "/etc/nginx/sites-available/gpms" as nginx_conf
	component GPMS as gpms
	component hypercorn
	node systemd <<daemon>>
}

Browser --- nginx: HTTPS
nginx -- hypercorn
nginx <- nginx_conf: configure
hypercorn - systemd: run instance
systemd <- systemd_conf: configure
hypercorn -- gpms
gpms -- db
@enduml
